package dev.hyaena_technologies.calculate_engine.theme

import androidx.compose.ui.graphics.Color

// Custom Colors
// val seed: Color = Color(0xFF008A39)
// val CustomColor: Color = Color(0xFFBF5A00)
// val light_CustomColor: Color = Color(0xFF994700)
// val light_onCustomColor: Color = Color(0xFFFFFFFF)
// val light_CustomColorContainer: Color = Color(0xFFFFDBC8)
// val light_onCustomColorContainer: Color = Color(0xFF321300)
// val dark_CustomColor: Color = Color(0xFFFFB68B)
// val dark_onCustomColor: Color = Color(0xFF522300)
// val dark_CustomColorContainer: Color = Color(0xFF753400)
// val dark_onCustomColorContainer: Color = Color(0xFFFFDBC8)

// Material Design Theme Dark
val md_theme_dark_primary: Color = Color(0xFF6DDD81)
val md_theme_dark_onPrimary: Color = Color(0xFF003913)
val md_theme_dark_primaryContainer: Color = Color(0xFF00531F)
val md_theme_dark_onPrimaryContainer: Color = Color(0xFF8AFA9A)
val md_theme_dark_secondary: Color = Color(0xFFFFB1C8)
val md_theme_dark_onSecondary: Color = Color(0xFF650033)
val md_theme_dark_secondaryContainer: Color = Color(0xFF8E004A)
val md_theme_dark_onSecondaryContainer: Color = Color(0xFFFFD9E2)
val md_theme_dark_tertiary: Color = Color(0xFFFFB1C8)
val md_theme_dark_onTertiary: Color = Color(0xFF650033)
val md_theme_dark_tertiaryContainer: Color = Color(0xFF8E004A)
val md_theme_dark_onTertiaryContainer: Color = Color(0xFFFFD9E2)
val md_theme_dark_error: Color = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer: Color = Color(0xFF93000A)
val md_theme_dark_onError: Color = Color(0xFF690005)
val md_theme_dark_onErrorContainer: Color = Color(0xFFFFDAD6)
val md_theme_dark_background: Color = Color(0xFF001B3D)
val md_theme_dark_onBackground: Color = Color(0xFFD6E3FF)
val md_theme_dark_surface: Color = Color(0xFF001B3D)
val md_theme_dark_onSurface: Color = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant: Color = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant: Color = Color(0xFFC1C9BE)
val md_theme_dark_outline: Color = Color(0xFF8B9389)
val md_theme_dark_inverseOnSurface: Color = Color(0xFF001B3D)
val md_theme_dark_inverseSurface: Color = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary: Color = Color(0xFF006E2C)

// Material Design Theme Dark Shadows
// val md_theme_dark_shadow: Color = Color(0xFF000000)

val md_theme_dark_surfaceTint: Color = Color(0xFF6DDD81)
val md_theme_dark_outlineVariant: Color = Color(0xFF424940)
val md_theme_dark_scrim: Color = Color(0xFF000000)

// Material Design Theme Light
val md_theme_light_primary: Color = Color(0xFF006E2C)
val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer: Color = Color(0xFF8AFA9A)
val md_theme_light_onPrimaryContainer: Color = Color(0xFF002108)
val md_theme_light_secondary: Color = Color(0xFFB90063)
val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer: Color = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer: Color = Color(0xFF3E001D)
val md_theme_light_tertiary: Color = Color(0xFFB90063)
val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer: Color = Color(0xFFFFD9E2)
val md_theme_light_onTertiaryContainer: Color = Color(0xFF3E001D)
val md_theme_light_error: Color = Color(0xFFBA1A1A)
val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6)
val md_theme_light_onError: Color = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer: Color = Color(0xFF410002)
val md_theme_light_background: Color = Color(0xFFFDFBFF)
val md_theme_light_onBackground: Color = Color(0xFF001B3D)
val md_theme_light_surface: Color = Color(0xFFFDFBFF)
val md_theme_light_onSurface: Color = Color(0xFF001B3D)
val md_theme_light_surfaceVariant: Color = Color(0xFFDDE5D9)
val md_theme_light_onSurfaceVariant: Color = Color(0xFF424940)
val md_theme_light_outline: Color = Color(0xFF727970)
val md_theme_light_inverseOnSurface: Color = Color(0xFFECF0FF)
val md_theme_light_inverseSurface: Color = Color(0xFF003062)
val md_theme_light_inversePrimary: Color = Color(0xFF6DDD81)

// Material Design Theme Light Shadows
// val md_theme_light_shadow: Color = Color(0xFF000000)

val md_theme_light_surfaceTint: Color = Color(0xFF006E2C)
val md_theme_light_outlineVariant: Color = Color(0xFFC1C9BE)
val md_theme_light_scrim: Color = Color(0xFF000000)
